#
# linux/drivers/rknand/Makefile
#
# $Id: Makefile,v 1.3 2011/01/21 10:12:56 Administrator Exp $
#
$(obj)/rk30xxnand_ko.o:
	@cp drivers/rknand/rk30xxnand_ko.lib drivers/rknand/rk30xxnand_ko.o
obj-$(CONFIG_BLOCK_RKNAND)	+= rk30xxnand_ko.o