# ROCKCHIP Platform Support
snd-soc-rockchip-i2s-objs := rockchip_i2s.o
snd-soc-rockchip-spdif-objs := rockchip_spdif.o

obj-$(CONFIG_SND_SOC_ROCKCHIP_I2S) += snd-soc-rockchip-i2s.o
obj-$(CONFIG_SND_SOC_ROCKCHIP_SPDIF) += snd-soc-rockchip-spdif.o

# ROCKCHIP Machine Support
snd-soc-rockchip-rk3036-objs := rockchip_rk3036.o
snd-soc-rockchip-spdif-card-objs := rockchip_spdif_card.o

obj-$(CONFIG_SND_SOC_ROCKCHIP_RK3036) += snd-soc-rockchip-rk3036.o
obj-$(CONFIG_SND_SOC_ROCKCHIP_SPDIF_CARD) += snd-soc-rockchip-spdif-card.o
