# ROCKCHIP Platform Support
snd-soc-i2s-objs := rockchip_i2s.o

# ROCKCHIP Machine Support
snd-soc-rockchip-rk3036-objs := rockchip_rk3036.o

obj-$(CONFIG_SND_SOC_ROCKCHIP_RK3036) += snd-soc-rockchip-rk3036.o
obj-$(CONFIG_SND_SOC_ROCKCHIP_I2S) += snd-soc-i2s.o
